title:        Parth Desai
tagline:      'Who needs a tag!'
description:  'Blog about Software engineering' 
url:          https://parthdesai.me
version:      1.1.0
author:
  name:       'Parth Desai'
  email:      'mail@parthdesai.me'

# owner/author information
owner:
  name:           Parth Desai
  avatar:         <your avatar>
  email:          mail@parthdesai.me
  # Social networking links used in footer. Update and remove as you like.
  github: parthdesai
  # For Google Authorship https://plus.google.com/authorship

# Analytics and webmaster tools stuff goes here
google_analytics: UA-40854387-1
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

google_verify: EAa0ohLWzXfnpjSw5_EJ13LNvbNxA7OHGPcwxNqehgg

highlighter: rouge

markdown:     kramdown
permalink:    pretty
paginate:     5
