title:        Vinit Kumar
tagline:      'Web, Programming and Life'
description:  'Personal blog of a Web Developer'
url:          http://vinitkumar.me
version:      1.1.0
author:
  name:       'Vinit Kumar'
  email:      'vinit.kumar@changer.nl'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
